version: '3'
services:
  auth-db:
    image: postgres
    container_name: auth-db
    restart: always
    environment:
      - POSTGRES_DB=auth-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - 5433:5432

  product-db:
    image: postgres
    container_name: product-db
    restart: always
    environment:
      - POSTGRES_DB=product-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - 5434:5432
  
  sales_rabbit:
    image: rabbitmq:3-management
    container_name: sales_rabbit
    ports:
      - 5672:5672
      - 15672:15672
      - 25676:25676
  
  auth-api:
    image: jeffersonpcinfo/auth-api
    container_name: auth-api
    environment:
      - PORT=8080
    ports:
      - 8080:8080

  sales-api:
    image: jeffersonpcinfo/sales-api
    container_name: sales-api
    environment:
      - PORT=8082
    ports:
      - 8082:8082

  product-api:
    image: jeffersonpcinfo/product-api
    container_name: product-api
    environment:
      - PORT=8081
    ports:
      - 8081:8081
