INSERT INTO CATEGORY (ID, NAME) VALUES (100, 'Comic Books');
INSERT INTO CATEGORY (ID, NAME) VALUES (200, 'Movies');
INSERT INTO CATEGORY (ID, NAME) VALUES (300, 'Books');

INSERT INTO SUPPLIER (ID, NAME) VALUES (100, 'Panini Comics');
INSERT INTO SUPPLIER (ID, NAME) VALUES (200, 'Amazon');

INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY)
    VALUES (100, 'Crise nas Infinitas Terras', 100, 100, 10);
INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY)
    VALUES (200, 'Interestelar', 200, 200, 5);
INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY)
    VALUES (300, 'Harry Potter', 200, 300, 3);